# PYTHON LAB PART 11-12

## Reading files in Python

### Download data

In [1]:
# Download Example file

!wget -O /resources/data/Example1.txt https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/labs/example1.txt

--2020-10-13 13:57:05--  https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/labs/example1.txt
Resolving s3-api.us-geo.objectstorage.softlayer.net (s3-api.us-geo.objectstorage.softlayer.net)... 67.228.254.196
Connecting to s3-api.us-geo.objectstorage.softlayer.net (s3-api.us-geo.objectstorage.softlayer.net)|67.228.254.196|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 45 [text/plain]
Saving to: ‘/resources/data/Example1.txt’

/resources/data/Exa 100%[===================>]      45  --.-KB/s    in 0s      

2020-10-13 13:57:05 (32.8 MB/s) - ‘/resources/data/Example1.txt’ saved [45/45]



### Reading Text Fimport os



In [63]:
import os
cwd = os.getcwd()  # Get the current working directory (cwd)
files = os.listdir(cwd)  # Get all the files in that directory
print("Files in %r: %s" % (cwd, files))

Files in '/resources/labs/PY0101EN': ['PY0101EN-1-1-Types.ipynb', 'PY0101EN-3-3-Functions.ipynb', 'PY0101EN-2-4-Sets.ipynb', 'PY0101EN-3-4-Classes.ipynb', 'PY0101EN-4-1-ReadFile.ipynb', '.ipynb_checkpoints', 'PY0101EN-2-1-Tuples.ipynb', 'PY0101EN-3-1-Conditions.ipynb', 'PY0101EN-2-3-Dictionaries.ipynb', 'PythonLab part 5-6.ipynb', 'PythonLab part 3-4.ipynb', 'PythonLab part 1-2.ipynb', 'PythonLab part 7-8.ipynb', 'PythonLab part 9-10.ipynb', 'PythonLab part 11-12.ipynb', 'PY0101EN-1-2-Strings.ipynb', 'PY0101EN-3-2-Loops.ipynb', 'PY0101EN-2-2-Lists.ipynb']


In [65]:
# Read the Example1.txt

file = ("file.txt")
file1 = open(file, "r")

In [66]:
# Print the path of file

file1.name

'file.txt'

In [67]:
# Print the mode of file, either 'r' or 'w'

file1.mode

'r'

In [68]:
# Read the file

FileContent = file1.read()
FileContent

'Attempt 1\n\nOpen file.txt in python '

In [69]:
# Print the file with '\n' as a new line

print(FileContent)

Attempt 1

Open file.txt in python 


In [70]:
# Type of file content

type(FileContent)

str

In [71]:
# Close file after finish

file1.close()

In [73]:
# Open file using with

with open(file, "r") as file1:
    FileContent = file1.read()
    print(FileContent)

FileNotFoundError: [Errno 2] No such file or directory: 'file.txt'

In [17]:
# Verify if the file is closed

file1.closed

True

In [18]:
# See the content of file

print(FileContent)

This is line 1 
This is line 2
This is line 3


In [19]:
# Read first four characters

with open(example1, "r") as file1:
    print(file1.read(4))

This


In [20]:
# Read certain amount of characters

with open(example1, "r") as file1:
    print(file1.read(4))
    print(file1.read(4))
    print(file1.read(7))
    print(file1.read(15))

This
 is 
line 1 

This is line 2


In [21]:
# Read certain amount of characters

with open(example1, "r") as file1:
    print(file1.read(16))
    print(file1.read(5))
    print(file1.read(9))

This is line 1 

This 
is line 2


In [22]:
# Read one line

with open(example1, "r") as file1:
    print("first line: " + file1.readline())

first line: This is line 1 



In [23]:
# Iterate through the lines

with open(example1,"r") as file1:
        i = 0;
        for line in file1:
            print("Iteration", str(i), ": ", line)
            i = i + 1;

Iteration 0 :  This is line 1 

Iteration 1 :  This is line 2

Iteration 2 :  This is line 3


In [24]:
# Read all lines and save as a list

with open(example1, "r") as file1:
    FileasList = file1.readlines()

In [25]:
# Print the first line

FileasList[0]

'This is line 1 \n'

In [26]:
# Print the second line

FileasList[1]

'This is line 2\n'

In [27]:
# Print the third line

FileasList[2]

'This is line 3'

## Writing Files in Python


In [1]:
# Write line to file

with open('/resources/data/Example2.txt', 'w') as writefile:
    writefile.write("This is line A")

In [2]:
# Read file

with open('/resources/data/Example2.txt', 'r') as testwritefile:
    print(testwritefile.read())

This is line A


In [21]:
# Write lines to file

with open('/resources/data/Example2.txt', 'w') as writefile:
    writefile.write("This is line A\n")
    writefile.write("This is line B\n")
    writefile.write("this line is personal\n")

In [22]:
# Check whether write to file

with open('/resources/data/Example2.txt', 'r') as testwritefile:
    print(testwritefile.read())

This is line A
This is line B
this line is personal



In [23]:
# Write a new line to text file

with open('/resources/data/Example2.txt', 'a') as testwritefile:
    testwritefile.write("This is line C\n")

In [24]:
# Verify if the new line is in the text file

with open('/resources/data/Example2.txt', 'r') as testwritefile:
    print(testwritefile.read())

This is line A
This is line B
this line is personal
This is line C



In [31]:
# Sample list of text

Lines = ["This is line A\n", "This is line B\n", 
         "this line is personal\n", "This is line C\n"]
Lines

['This is line A\n',
 'This is line B\n',
 'this line is personal\n',
 'This is line C\n']

In [32]:
# Write the strings in the list to text file

with open('Example2.txt', 'w') as writefile:
    for line in Lines:
        print(line)
        writefile.write(line)

This is line A

This is line B

this line is personal

This is line C



In [33]:
# Verify if writing to file is successfully executed

with open('Example2.txt', 'r') as testwritefile:
    print(testwritefile.read())

This is line A
This is line B
this line is personal
This is line C



In [34]:
# Append the line to the file

with open('Example2.txt', 'a') as testwritefile:
    testwritefile.write("This is line D\n")

In [35]:
# Verify if the appending is successfully executed

with open('Example2.txt', 'r') as testwritefile:
    print(testwritefile.read())

This is line A
This is line B
this line is personal
This is line C
This is line D



### Copy a File

In [12]:
# Copy file to another

with open('Example2.txt','r') as readfile:
    with open('Example3.txt','w') as writefile:
          for line in readfile:
                writefile.write(line)

In [13]:
# Verify if the copy is successfully executed

with open('Example3.txt','r') as testwritefile:
    print(testwritefile.read())

This is line A
This is line B
This is line C
This is line D



In [14]:
# Writing a file and saving in .txt format
file1 = open("myfile.txt","w")
L = ["This is Delhi \n","This is Paris \n","This is London \n"]
file1.writelines(L)
file1.close()

# NUMPY IN PYTHON

In [1]:
# Import the libraries

import time 
import sys
import numpy as np 

import matplotlib.pyplot as plt
%matplotlib inline  

In [2]:
# Plotting functions

def Plotvec1(u, z, v):
    
    ax = plt.axes()
    ax.arrow(0, 0, *u, head_width=0.05, color='r', head_length=0.1)
    plt.text(*(u + 0.1), 'u')
    
    ax.arrow(0, 0, *v, head_width=0.05, color='b', head_length=0.1)
    plt.text(*(v + 0.1), 'v')
    ax.arrow(0, 0, *z, head_width=0.05, head_length=0.1)
    plt.text(*(z + 0.1), 'z')
    plt.ylim(-2, 2)
    plt.xlim(-2, 2)

def Plotvec2(a,b):
    ax = plt.axes()
    ax.arrow(0, 0, *a, head_width=0.05, color ='r', head_length=0.1)
    plt.text(*(a + 0.1), 'a')
    ax.arrow(0, 0, *b, head_width=0.05, color ='b', head_length=0.1)
    plt.text(*(b + 0.1), 'b')
    plt.ylim(-2, 2)
    plt.xlim(-2, 2)

In [3]:
# Create a python list

a = ["0", 1, "two", "3", 4]

In [4]:
# Print each element

print("a[0]:", a[0])
print("a[1]:", a[1])
print("a[2]:", a[2])
print("a[3]:", a[3])
print("a[4]:", a[4])

a[0]: 0
a[1]: 1
a[2]: two
a[3]: 3
a[4]: 4


In [5]:
# import numpy library

import numpy as np 

In [6]:
# Create a numpy array

a = np.array([0, 1, 2, 3, 4])
a

array([0, 1, 2, 3, 4])

In [7]:
# Print each element

print("a[0]:", a[0])
print("a[1]:", a[1])
print("a[2]:", a[2])
print("a[3]:", a[3])
print("a[4]:", a[4])

a[0]: 0
a[1]: 1
a[2]: 2
a[3]: 3
a[4]: 4


In [8]:
# Check the type of the array

type(a)

numpy.ndarray

In [9]:
# Check the type of the values stored in numpy array

a.dtype

dtype('int64')

In [10]:
# Create numpy array

c = np.array([20, 1, 2, 3, 4])
c

array([20,  1,  2,  3,  4])

In [11]:
# Assign the first element to 100

c[0] = 100
c

array([100,   1,   2,   3,   4])

In [12]:
# Slicing the numpy array

d = c[1:4]
d

array([1, 2, 3])

In [13]:
# Create the index list

select = [0, 2, 3]

In [14]:
# Use List to select elements

d = c[select]
d

array([100,   2,   3])

In [15]:
u = np.array([1, 0])
u

array([1, 0])

In [16]:
v = np.array([0, 1])
v

array([0, 1])

In [21]:
# Create a list

a = [[11, 12, 13], [21, 22, 23], [31, 32, 33]]
a

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]

In [22]:
# Convert list to Numpy Array
# Every element is the same type

A = np.array(a)
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [23]:
# Access the element on the second row and third column

A[1, 2]

23

In [24]:
# Create a numpy array X

X = np.array([[1, 0], [0, 1]]) 
X

array([[1, 0],
       [0, 1]])

In [25]:
# Create a numpy array Y

Y = np.array([[2, 1], [1, 2]]) 
Y

array([[2, 1],
       [1, 2]])

In [26]:
# Add X and Y

Z = X + Y
Z

array([[3, 1],
       [1, 3]])